# Generated by Django 3.2.25 on 2024-10-25 13:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241024_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='result',
            name='compatibility_score',
        ),
        migrations.RemoveField(
            model_name='result',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='result',
            name='matched_user',
        ),
        migrations.AddField(
            model_name='answer',
            name='responses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='result',
            name='matching_data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(default=200000000, unique=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
